// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvyaaxwaqqcefjdkjnyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2eWFheHdhcXFjZWZqZGtqbnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzA2MDQsImV4cCI6MjA3MTgwNjYwNH0.5pcED6NeCq8-LlaY4jvBofWOoGDIaITpFG6E8ztHKIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});